### ISSUE TITLE
assertion "Invalid mbox" failed:

### ISSUE THREAD

**Issue by mctosima** [mctosima/cfiot-dumbbell-ntust-team1#1]
The `MQTT + Face Detection wo Server` code left some errors :

`16:13:59.081 -> WELCOME Martin2
16:13:59.081 -> Attempting MQTT
16:13:59.081 -> assertion "Invalid mbox" failed: file "/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/api/tcpip.c", line 374, function: tcpip_send_msg_wait_sem
16:13:59.116 -> abort() was called at PC 0x400ddb37 on core 1
16:13:59.116 -> 
16:13:59.116 -> ELF file SHA256: 0000000000000000
16:13:59.116 -> 
16:13:59.116 -> Backtrace: 0x4008a748:0x3ffb1ca0 0x4008a9c1:0x3ffb1cc0 0x400ddb37:0x3ffb1ce0 0x400f7da3:0x3ffb1d10 0x400f783d:0x3ffb1d40 0x400f79f0:0x3ffb1d60 0x400efc14:0x3ffb1da0 0x400d3870:0x3ffb1dc0 0x400d3285:0x3ffb1e10 0x40116fe9:0x3ffb1e40 0x400d3f1d:0x3ffb1e60 0x400d4119:0x3ffb1ea0 0x400d2c2e:0x3ffb1ed0 0x400d2fa9:0x3ffb1ef0 0x400d4ead:0x3ffb1fb0 0x4008c652:0x3ffb1fd0
16:13:59.154 -> 
16:13:59.154 -> Rebooting...
16:13:59.154 -> ets Jun  8 2016 00:22:57
16:13:59.154 -> 
16:13:59.154 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
16:13:59.154 -> configsip: 0, SPIWP:0xee
16:13:59.154 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
16:13:59.154 -> mode:DIO, clock div:1
16:13:59.154 -> load:0x3fff0018,len:4
16:13:59.154 -> load:0x3fff001c,len:1216
16:13:59.154 -> ho 0 tail 12 room 4
16:13:59.190 -> load:0x40078000,len:10944
16:13:59.190 -> load:0x40080400,len:6388
16:13:59.190 -> entry 0x400806b4
16:14:00.676 -> 
16:14:01.374 -> delete_faces
16:14:01.374 -> listface:yoga
16:14:01.374 -> listface:Martin
16:14:01.374 -> listface:Martin2
16:14:01.374 -> STREAMING
16:14:01.587 -> NO FACE DETECTED
`
<img width="1151" alt="Screen Shot 2021-06-06 at 16 15 08" src="https://user-images.githubusercontent.com/22334778/120917639-e7468880-c6e2-11eb-8141-10d763f06168.png">

This code show up when a known face detected

**Comment by zefir-o** [comment]
Hi, @mctosima,
How have you fixed this issue?
